#!/bin/bash

set -ex


pip install .

git clone https://github.com/glue-viz/glue
(cd glue; pip install .)

# jupyter labextension install @jupyter-widgets/jupyterlab-manager

pip uninstall ipyvolume -y
git clone https://github.com/maartenbreddels/ipyvolume/
pushd ipyvolume

pip install -v .
# jupyter labextension install js --no-build
# jupyter labextension install jupyter-threejs --no-build
popd

pip uninstall bqplot -y
git clone https://github.com/maartenbreddels/bqplot/
pushd bqplot
git checkout scatter_webgl
pip install .
# jupyter labextension install js
popd

# jupyter labextension build
