#!/bin/bash

set -ex


pip install .

git clone https://github.com/glue-viz/glue
(cd glue; pip install .)

jupyter labextension install @jupyter-widgets/jupyterlab-manager

pip uninstall ipyvolume -y
git clone https://github.com/maartenbreddels/ipyvolume/
pushd ipyvolume
pip install .
jupyter labextension install js
jupyter labextension install jupyter-threejs
popd

git clone https://github.com/maartenbreddels/bqplot/
pushd bqplot
git checkout scatter_webgl
pip install .
jupyter labextension install js
popd
