name: glue-jupyter
dependencies:
  - pyqt
  - nomkl
  - nodejs
  - pip:
    - jupyterlab ==0.34
    - notebook >=5.5
    - ipywidgets
    - ipympl
    - pythreejs
    - ipyvolume >=0.5.1
    - https://github.com/glue-viz/glue/archive/master.zip
    - https://github.com/glue-viz/glue-vispy-viewers/archive/master.zip
