#!/bin/bash

set -ex

# keep git happy
git config --global user.email "bin@der.com"
git config --global user.name "Bin Der"

pip install .

# git clone https://github.com/glue-viz/glue
# (cd glue; pip install .)

jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-threejs ipyvolume@^0.5.0-beta.1 --no-build

# pip uninstall ipyvolume -y
# git clone https://github.com/maartenbreddels/ipyvolume/
# pushd ipyvolume
# pip install -v .
# jupyter labextension install js --no-build
# jupyter labextension install jupyter-threejs --no-build
# popd



pip uninstall bqplot -y
git clone https://github.com/maartenbreddels/bqplot/
pushd bqplot
git checkout scatter_webgl
pip install .
jupyter labextension install js --no-build
popd

git clone https://github.com/maartenbreddels/ipymaterialui/
pushd ipymaterialui
pip install .
jupyter labextension install js --no-build
popd


git clone https://github.com/glue-viz/ipyastroimage/
pushd ipyastroimage
pip install .
jupyter labextension install js --no-build
popd

jupyter lab build
